// 作品集数据
const portfolioData = [
    // 个人简介
    {
        id: 'resume',
        title: '个人简历',
        description: '重庆大学李云飞的个人简历，包含教育背景、技能、项目经历等。',
        type: 'pdf',
        category: 'about',
        filePath: '个人简历/重庆大学-李云飞-简历.pdf',
        tags: ['简历', '教育', '工作经历'],
    },
    {
        id: 'about-me',
        title: '关于我的经历',
        description: '详细的自述文档，介绍个人经历、动机和职业目标。',
        type: 'pdf',
        category: 'about',
        filePath: '自述/关于我的经历.pdf',
        tags: ['自述', '个人经历'],
    },
    {
        id: 'personal-photo',
        title: '个人照片',
        description: '个人形象照片',
        type: 'image',
        category: 'about',
        filePath: '个人照片/个人照片.JPG',
        tags: ['照片'],
    },

    // 实践项目
    {
        id: 'hospital-automation',
        title: '妇幼保健院自动化流程',
        description: '使用PowerQuery为妇幼保健院搭建自动化数据处理流程的Excel模板。',
        type: 'other',
        category: 'project',
        filePath: '实践项目：为妇幼保健院搭建自动化流程/powerquery自动化模版.xlsx',
        tags: ['PowerQuery', '自动化', '数据分析', 'Excel'],
    },

    // APP项目
    {
        id: 'period-app',
        title: '生理周期App',
        description: '一款帮助女性跟踪生理周期的Android应用，包含多个版本和界面展示。',
        type: 'apk',
        category: 'app',
        filePath: 'APP/生理周期App项目/生理周期App-debug-v1.apk',
        thumbnail: 'APP/生理周期App项目/界面展示/1.jpg',
        tags: ['Android', '移动应用', '健康'],
    },
    // APP截图
    {
        id: 'period-app-ui1',
        title: '生理周期App界面1',
        description: '应用主界面截图',
        type: 'image',
        category: 'app',
        filePath: 'APP/生理周期App项目/界面展示/1.jpg',
        tags: ['界面', 'UI设计'],
    },
    {
        id: 'period-app-ui2',
        title: '生理周期App界面2',
        description: '数据统计界面截图',
        type: 'image',
        category: 'app',
        filePath: 'APP/生理周期App项目/界面展示/2.jpg',
        tags: ['界面', '数据可视化'],
    },
    {
        id: 'period-app-ui3',
        title: '生理周期App界面3',
        description: '设置界面截图',
        type: 'image',
        category: 'app',
        filePath: 'APP/生理周期App项目/界面展示/3.jpg',
        tags: ['界面', '设置'],
    },
    {
        id: 'period-app-ui4',
        title: '生理周期App界面4',
        description: '日历视图截图',
        type: 'image',
        category: 'app',
        filePath: 'APP/生理周期App项目/界面展示/4.jpg',
        tags: ['界面', '日历'],
    },
    {
        id: 'period-app-ui5',
        title: '生理周期App界面5',
        description: '通知设置截图',
        type: 'image',
        category: 'app',
        filePath: 'APP/生理周期App项目/界面展示/5.jpg',
        tags: ['界面', '通知'],
    },
    {
        id: 'period-app-ui6',
        title: '生理周期App界面6',
        description: '关于页面截图',
        type: 'image',
        category: 'app',
        filePath: 'APP/生理周期App项目/界面展示/6.jpg',
        tags: ['界面', '关于'],
    },

    // 学习过程产出
    {
        id: 'ai-learning-handbook',
        title: 'AI系统化学习手册',
        description: '系统化学习人工智能的指南手册，涵盖基础理论和实践方法。',
        type: 'pdf',
        category: 'learning',
        filePath: '学习过程产出/AI系统化学习手册.pdf',
        tags: ['AI', '学习', '手册'],
    },
    {
        id: 'low-budget-chatbot',
        title: '低预算聊天机器人创业：前期研究',
        description: '关于低成本构建聊天机器人创业项目的方向层研究。',
        type: 'pdf',
        category: 'learning',
        filePath: '学习过程产出/低预算聊天机器人创业：前期研究（方向层）.pdf',
        tags: ['聊天机器人', '创业', '研究'],
    },
    {
        id: 'data-analysis-notes',
        title: '数据分析学习笔记',
        description: '从入门到实践的数据分析学习笔记，包含实战案例。',
        type: 'pdf',
        category: 'learning',
        filePath: '学习过程产出/我的数据分析学习笔记：从入门到实践之路.pdf',
        tags: ['数据分析', '学习笔记', '实践'],
    },
    {
        id: 'sql-notes',
        title: 'SQL学习笔记',
        description: 'SQL数据库查询语言的学习笔记。',
        type: 'pdf',
        category: 'learning',
        filePath: '学习过程产出/SQL 学习笔记.pdf',
        tags: ['SQL', '数据库', '学习笔记'],
    },

    // 小程序&智能体&工作流
    {
        id: 'ai-travel-planning',
        title: 'AI旅行规划',
        description: '使用AI进行旅行规划的智能体界面展示。',
        type: 'image',
        category: 'project',
        filePath: '小程序&智能体&工作流/AI旅行规划.jpg',
        tags: ['AI', '旅行规划', '智能体'],
    },
    {
        id: 'mini-app-collection1',
        title: '小程序&应用合集1',
        description: '开发的小程序和应用集合截图。',
        type: 'image',
        category: 'project',
        filePath: '小程序&智能体&工作流/小程序&应用合集.jpg',
        tags: ['小程序', '应用', '集合'],
    },
    {
        id: 'mini-app-collection2',
        title: '小程序&应用合集2',
        description: '更多小程序和应用集合截图。',
        type: 'image',
        category: 'project',
        filePath: '小程序&智能体&工作流/小程序&应用合集2.jpg',
        tags: ['小程序', '应用', '集合'],
    },
    {
        id: 'workflow-example',
        title: '工作流示例',
        description: '自动化工作流的示例展示。',
        type: 'image',
        category: 'project',
        filePath: '小程序&智能体&工作流/工作流示例.jpg',
        tags: ['工作流', '自动化'],
    },
    {
        id: 'paper-writing-assistant',
        title: '论文辅助写作智能体',
        description: '辅助学术论文写作的AI智能体界面。',
        type: 'image',
        category: 'project',
        filePath: '小程序&智能体&工作流/论文辅助写作智能体.jpg',
        tags: ['论文写作', 'AI智能体', '学术'],
    },

    // 论文
    {
        id: 'bayesian-flow-sorting',
        title: '贝叶斯流排序框架',
        description: '关于贝叶斯流排序框架的研究论文。',
        type: 'pdf',
        category: 'paper',
        filePath: '论文/贝叶斯流排序框架.pdf',
        tags: ['贝叶斯', '排序算法', '论文'],
    },

    // 视频创作
    {
        id: 'video-showcase',
        title: '视频创作展示',
        description: '个人视频创作作品展示。',
        type: 'image',
        category: 'video',
        filePath: '视频创作/视频展示.jpg',
        tags: ['视频创作', '多媒体', '展示'],
    },
];

// 分类映射
const categories = [
    { id: 'about', name: '个人简介' },
    { id: 'project', name: '项目展示' },
    { id: 'app', name: '移动应用' },
    { id: 'learning', name: '学习成果' },
    { id: 'paper', name: '学术论文' },
    { id: 'video', name: '视频创作' },
];